SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../hdl/dut.v
VCD_FILE = xor_waveform.fst
WAVES =1
TOPLEVEL = dut
MODULE = dut_test
include $(shell cocotb-config --makefiles)/Makefile.sim
